### ISSUE TITLE
Doc link from Servo -> Sevos is a 404

### ISSUE THREAD

**Issue by makenai** [j5js/johnny-five.io#86]
Looks like the link to the Servos class here goes to a 404:

http://johnny-five.io/api/servo/

It goes to http://johnny-five.io/api/servo/servos when it should go to http://johnny-five.io/api/servos

It works correctly within the wiki. I remember you telling me that the website is generated from the wiki, but I'm not sure how that's done, if you give me a pointer I can look into a fix!

**Comment by rwaldron** [comment]
Ugh. The content in question is:

```
For working with multiple servos check out the [Servos](servos) class.
```

...in the wiki. There must be a simple way to fix this :|

**Comment by rwaldron** [comment]
Indeed there is! Looks like Led just uses a fully qualified path: 

```
- [Led.Digits](https://github.com/rwaldron/johnny-five/wiki/led.digits)
- [Led.Matrix](https://github.com/rwaldron/johnny-five/wiki/led.matrix)
- [Led.RGB](https://github.com/rwaldron/johnny-five/wiki/led.rgb)
- [Leds](https://github.com/rwaldron/johnny-five/wiki/leds)
```

**Comment by rwaldron** [comment]
Fixed! Thanks for filing <3

http://johnny-five.io/api/servo/
